name: CI Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build Release
        # We removed the "lint" checks and "D warnings" here
        run: cargo build --release --all-features

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: arnis-windows-custom
          path: target/release/arnis.exe
